In [34]:
import pandas as pd
import numpy as np
import zipfile

In [35]:
with zipfile.ZipFile('/content/drive/MyDrive/spaceship-titanic.zip') as z:
  print(*z.namelist(), sep='\n')

sample_submission.csv
test.csv
train.csv


In [36]:
with zipfile.ZipFile('/content/drive/MyDrive/spaceship-titanic.zip') as z:
  with z.open('train.csv') as principal:
    train = pd.read_csv(principal)

In [37]:
with zipfile.ZipFile('/content/drive/MyDrive/spaceship-titanic.zip') as t:
  with t.open('test.csv') as pr:
    test = pd.read_csv(pr)

In [38]:
train.shape

(8693, 14)

In [39]:
test.shape

(4277, 13)

In [40]:
train.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [41]:
train['Destination'].unique()

array(['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e', nan], dtype=object)

In [42]:
train.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [43]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


In [44]:
train.dropna(axis=0, inplace=True)

In [45]:
train.shape

(6606, 14)

In [46]:
train.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [47]:
COL = ['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP']
x = train[COL]
y = train['Transported']

In [48]:
x

HomePlanet CryoSleep     Cabin    Destination   Age    VIP
0        Europa     False     B/0/P    TRAPPIST-1e  39.0  False
1         Earth     False     F/0/S    TRAPPIST-1e  24.0  False
2        Europa     False     A/0/S    TRAPPIST-1e  58.0   True
3        Europa     False     A/0/S    TRAPPIST-1e  33.0  False
4         Earth     False     F/1/S    TRAPPIST-1e  16.0  False
...         ...       ...       ...            ...   ...    ...
8688     Europa     False    A/98/P    55 Cancri e  41.0   True
8689      Earth      True  G/1499/S  PSO J318.5-22  18.0  False
8690      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False
8691     Europa     False   E/608/S    55 Cancri e  32.0  False
8692     Europa     False   E/608/S    TRAPPIST-1e  44.0  False

[6606 rows x 6 columns]

In [49]:
y

0       False
1        True
2       False
3       False
4        True
        ...  
8688    False
8689    False
8690     True
8691    False
8692     True
Name: Transported, Length: 6606, dtype: bool

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train, x_valid, y_train, y_valid = train_test_split(x, y, train_size=0.7)

In [52]:
x_train.shape

(4624, 6)

In [53]:
x_valid.shape

(1982, 6)

In [54]:
y_train.shape

(4624,)

In [55]:
y_valid.shape

(1982,)

In [56]:
colunas_numericas = [numericas for numericas in x_train.columns if x_train[numericas].dtypes in ['int64', 'float64']]
colunas_categoricas = [categoricas for categoricas in x_train.columns if x_train[categoricas].dtypes == 'object' and x_train[categoricas].nunique() < 10]

In [57]:
colunas_numericas

['Age']

In [58]:
colunas_categoricas

['HomePlanet', 'CryoSleep', 'Destination', 'VIP']

In [59]:
colunas = colunas_numericas + colunas_categoricas
x_train = x_train[colunas].copy()
x_valid = x_valid[colunas].copy()
X_teste = test[colunas].copy()

In [60]:
#dados numéricos, não tem imputacao, pois foram retirados números nulos

In [61]:
#dados categoricos

In [62]:
from sklearn.preprocessing import OrdinalEncoder

In [63]:
from sklearn.pipeline import Pipeline

In [64]:
from sklearn.preprocessing import OneHotEncoder

In [65]:
categoricos = Pipeline(steps=[
    ('Onehot', OneHotEncoder(handle_unknown='ignore', sparse=False))
])

In [66]:
from sklearn.impute import SimpleImputer

In [67]:
imputacao = SimpleImputer(strategy='median')

In [68]:
from sklearn.compose import ColumnTransformer

In [69]:
preprocessor = ColumnTransformer(transformers=[
    ('num', imputacao, colunas_numericas),
    ('cat', categoricos, colunas_categoricas)
])

In [70]:
from sklearn.ensemble import RandomForestRegressor

In [71]:
from sklearn.linear_model import LogisticRegression

In [72]:
modelo = LogisticRegression()

In [73]:
my_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('modelo', modelo)
])

In [74]:
my_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='median'),
                                                  ['Age']),
                                                 ('cat',
                                                  Pipeline(steps=[('Onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse=False))]),
                                                  ['HomePlanet', 'CryoSleep',
                                                   'Destination', 'VIP'])])),
                ('modelo', LogisticRegression())])

In [75]:
predicao = my_pipeline.predict(x_valid)
predicao

array([ True,  True,  True, ...,  True, False, False])

In [76]:
from sklearn.metrics import mean_absolute_error

In [77]:
#por ser booleano "true""false", a subtração via np não está rolando,necessita transformar
y_valid = y_valid.astype(np.float64)

In [78]:
#por ser booleano "true""false", a subtração via np não está rolando,necessita transformar
predicao = predicao.astype(np.float64)

In [79]:
mean_absolute_error(y_valid, predicao)

0.28809283551967707

In [80]:
from sklearn.model_selection import cross_val_score

In [81]:
y = y.astype(np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [82]:
validacao = -1 * cross_val_score(my_pipeline, x, y, cv=5, scoring='neg_mean_absolute_error')
validacao

array([0.28744327, 0.27403482, 0.3012869 , 0.28614686, 0.28084784])

In [83]:
validacao.mean()

0.28595193894507553

In [84]:
np.mean(validacao)

0.28595193894507553

In [85]:
X_teste.isnull().sum()

Age            91
HomePlanet     87
CryoSleep      93
Destination    92
VIP            93
dtype: int64

In [86]:
X_teste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          4186 non-null   float64
 1   HomePlanet   4190 non-null   object 
 2   CryoSleep    4184 non-null   object 
 3   Destination  4185 non-null   object 
 4   VIP          4184 non-null   object 
dtypes: float64(1), object(4)
memory usage: 167.2+ KB


In [87]:
x_valid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1982 entries, 735 to 2895
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          1982 non-null   float64
 1   HomePlanet   1982 non-null   object 
 2   CryoSleep    1982 non-null   object 
 3   Destination  1982 non-null   object 
 4   VIP          1982 non-null   object 
dtypes: float64(1), object(4)
memory usage: 92.9+ KB


In [88]:
X_teste.shape

(4277, 5)

In [89]:
my_pipeline.predict(X_teste)

array([ True, False,  True, ...,  True,  True,  True])

In [91]:
#versao feita retirando todos os nulos da base de dados de treino